replicaCount: 1

image:
  repository: ghcr.io/krishnakumar-sudala/notes-service/notes-service
  tag: "bab0e2659e2ad641657069780dce0b191ce10e71"
=======
  repository: ghcr.io/krishnakumar-sudala/notes-service
  tag: "bab0e2659e2ad641657069780dce0b191ce10e71"
>>>>>>> 45fe652ce25d6e8502c1f156ee0c1974731558b3
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

redis:
  host: "redis-master"
  port: 6379
  passwordSecretName: "redis"
  passwordSecretKey: "redis-password"
  password: "HN3ajAXaAW"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

route:
  enabled: true
  host: ""

serviceAccount:
  create: false
  name: ""
