apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "notes-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "notes-service.name" . }}
    spec:
      containers:
        - name: notes-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.passwordSecretName }}
                  key: {{ .Values.redis.passwordSecretKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
